workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
       


version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.2-stretch-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4
#       parallelism: 3

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum .Environment.requirements }}
                        - v1-dependencies-{{ checksum "requirements.txt" }}
            fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
          key: v1-dependencies-{{ checksum .Environment.requirements }}
      - run: pwd
# #       - run: cd user
      
#       - run:
#           name: run tests
#           command: |
#             . venv/bin/activate 
#             python3 test.py
            
#       - run:
#           name: test
#           command: |
#             . venv/bin/activate 
#             pwd 
            
      - run:
          name: echo hello world 
          command: |
            echo "hello world"
                          
            
           
#       - store_test_results:
#           path: test-reports     

#       - store_artifacts:
#           path: test-reports
#           destination: test-reports

  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
#       - run:
#           name: Deploy Master to Heroku
#           command: |
#             git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
            
#             #added a comment to push a fresh commit 
#             #trying to trigger a build 
            
            
                  # test test
                              # test test
      
            
            
